# Generated by Django 2.2.4 on 2019-08-18 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='hasil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('kondisi', models.CharField(max_length=25)),
                ('produk', models.CharField(max_length=255)),
                ('harga', models.BigIntegerField()),
                ('pelapak', models.CharField(max_length=255)),
                ('feedback', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=500)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bukalapak_hasil_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bukalapak_hasil_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
